server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

keycloak:
  realm: javatechie
  auth-server-url: http://localhost:8180/auth
  resource: springboot-keycloak
  public-client: true
  bearer-only: true